apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-go-server"
  labels:
    app: "api-go-server"
spec:
  selector:
    matchLabels:
      app: "api-go-server"
  replicas: 1
  template:
    metadata:
      name: "api-go-server"
      labels:
        app: "api-go-server"
    spec:
      containers:
        - name: "goserver"
          image: "heliandro/hello-go:v5.2"
          envFrom:
            - configMapRef:
                name: api-go-server-env

            - secretRef:
                name: apigoserver-secret

          volumeMounts:
            - mountPath: "/app/myfamily"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"