apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "api-go-server"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25 # somente na autoscaling/v1
  # metrics:   # somente na autoscaling/v2
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 30
